### PR TITLE
Only treat message content when searching URLs

### LINKED ISSUE #2638: URL Links in Template Messages Incorrectly Include Trailing Commas When Opened
### Description

When clicking URLs in messages formatted with the template {user}: {content}, {date}:
1. The displayed message appears correct:
   LBK: https://bearware.dk/beta, 5/5/2025 4:26 PM
2. The clickable link works, but incorrectly includes the trailing comma:
   Opens → https://bearware.dk/beta,
3. This causes "page not found" errors on many websites

### Technical Analysis:
• Problem occurs because the URL detector includes the comma as part of the link.
• The comma comes from the template (not the original message content).
• The parser should stop at whitespace/punctuation when detecting URLs

### Application

- [x] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [x] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Clicking should open just the clean URL:
https://bearware.dk/beta

### Actual behavior

When clicking URLs in messages formatted with the template {user}: {content}, {date}:
1. The link remains clickable/functional in the chat interface.
2. The web browser attempts to open the URL with the trailing comma included.
   - Example: Clicking https://bearware.dk/beta in the message:
     LBK: https://bearware.dk/beta, 5/5/2025 4:26 PM
   - Actually opens:
     https://bearware.dk/beta,
3. This results in:
   - Failed page loads (404 errors) on most websites
   - Broken functionality for URL parameters (#/?&)
   - Requires manual URL editing in the browser's address bar

### Steps to reproduce problem

1. Use template: {user}: {content}, {date}.
2. Post message containing a URL.
3. Click the URL in chat.
4. Observe browser attempts to open URL-with-comma.

### Workarounds
Modify template to add space before comma:
   {user}: {content} , {date}
### Impact
Breaks standard URL functionality for template-formatted messages.
### Priority
Medium - Affects usability but has workarounds.

### PR DESCRIPTION
**Pull request by CoBC**
Should fixed #2638

### CODE REVIEW

File: Client/qtTeamTalk/chattextlist.cpp [hunk 1]
```diff
@@ -268,7 +268,7 @@ QStringList ChatTextList::allUrls(const QString &text) const
 
 QString ChatTextList::currentUrl(const QListWidgetItem* item) const
 {
-    QString text = item->text();
+    QString text = item->data(Qt::UserRole + 3).toString();
```
Comment (bear101) [inline Client/qtTeamTalk/chattextlist.cpp:271]: Shouldn't here be a define of `Qt::UserRole + 3` item-data?

Comment (CoBC) [reply Client/qtTeamTalk/chattextlist.cpp:271]: UserRole + 3 is defined when we create items, e.g. line 195

Comment (bear101) [reply Client/qtTeamTalk/chattextlist.cpp:271]: OK, but then make a define for each item-data. Otherwise the next developer will forget to update all places where it's used.

Comment (CoBC) [reply Client/qtTeamTalk/chattextlist.cpp]: Is f816daa what you want?

**Comment by bear101** [comment]
Thanks. Should we release after I merge this one?

**Comment by CoBC** [comment]
Yes, I think the version is ready now
