### PR TITLE
Android: fix IPv6-only server connectivity

### LINKED ISSUE #1987: TeamTalk for Android cannot connect to IPv6 servers
### Discussed in https://github.com/BearWare/TeamTalk5/discussions/1986

<div type='discussions-op-text'>

<sup>Originally posted by **BaiRuoQiu** August 15, 2023</sup>
### Description

hi developer , my computer have public ipv6 address and teamtalk use the loopback address "::1" a ipv4 address "127.0.0.1" 
I test of them with android ios windows that  ipv4 can connect , ipv6 cannot But my other services can use IPv6 connections
so how can I use my ipv6 to connect server 
The following is my server configuration file, please take a look 
thanks~

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [X] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

_No response_

### Actual behavior

<?xml version="1.0" encoding="UTF-8" ?>
<teamtalk version="5.2">
    <general>
        <server-name>***</server-name>
        <motd>********************************</motd>
        <max-users>30</max-users>
        <auto-save>true</auto-save>
        <tcpport>16525</tcpport>
        <udpport>16526</udpport>
        <login-attempts>0</login-attempts>
        <max-logins-per-ipaddr>0</max-logins-per-ipaddr>
        <login-delay-msec>500</login-delay-msec>
        <bandwidth-limits>
            <voicetx-limit>0</voicetx-limit>
            <vidcaptx-limit>0</vidcaptx-limit>
            <mediafiletx-limit>0</mediafiletx-limit>
            <desktoptx-limit>0</desktoptx-limit>
            <totaltx-limit>0</totaltx-limit>
        </bandwidth-limits>
        <user-timeout>60</user-timeout>
        <certificate-file></certificate-file>
        <privatekey-file></privatekey-file>
        <trusted-certificate>
            <certificate-authority-file></certificate-authority-file>
            <certificate-authority-dir></certificate-authority-dir>
            <verify-peer>false</verify-peer>
            <verify-client-once>true</verify-client-once>
            <verify-depth>0</verify-depth>
        </trusted-certificate>
        <bind-ip>[::1]</bind-ip>
        <bind-ip>127.0.0.1</bind-ip>
    </general>
    <file-storage>
        <files-root>D:\team_talk_file_storage</files-root>
        <max-diskusage>16106127360</max-diskusage>
        <channel-diskquota>0</channel-diskquota>
    </file-storage>
    <logging>
        <server-log-maxsize>-1</server-log-maxsize>
        <server-log-events>67108863</server-log-events>
    </logging>
    <users>
        <user>
            <username>**********</username>
            <password>**********</password>
            <user-type>2</user-type>
            <user-rights>0</user-rights>
            <note />
            <userdata>0</userdata>
            <init-channel />
            <modified-time>2023/06/22 21:34</modified-time>
            <audiocodec-bps-limit>0</audiocodec-bps-limit>
            <abuse-prevention>
                <commands-limit>0</commands-limit>
                <commands-interval-msec>0</commands-interval-msec>
            </abuse-prevention>
            <channel-operator />
        </user>
        <user>
            <username>*********</username>
            <password>*********</password>
            <user-type>1</user-type>
            <user-rights>259591</user-rights>
            <note />
            <userdata>0</userdata>
            <init-channel />
            <modified-time>2023/06/22 21:34</modified-time>
            <audiocodec-bps-limit>0</audiocodec-bps-limit>
            <abuse-prevention>
                <commands-limit>0</commands-limit>
                <commands-interval-msec>0</commands-interval-msec>
            </abuse-prevention>
            <channel-operator />
        </user>
    </users>
    <serverbans />
    <permanent-channels>
        <channel>
            
            <channel-id>1</channel-id>
            <password />
            <topic>欢迎</topic>
            <diskquota>0</diskquota>
            <op-password />
            <max-users>1000</max-users>
            <channel-type>1</channel-type>
            <userdata>0</userdata>
            <audio-codec>
                <codec-type>3</codec-type>
                <samplerate>24000</samplerate>
                <channels>2</channels>
                <application>2049</application>
                <complexity>10</complexity>
                <fec>true</fec>
                <dtx>false</dtx>
                <bitrate>128000</bitrate>
                <vbr>true</vbr>
                <vbr-constraint>false</vbr-constraint>
                <framesize>960</framesize>
                <fpp>1</fpp>
            </audio-codec>
            <audio-config>
                <enable-agc>false</enable-agc>
                <gain-level>0</gain-level>
            </audio-config>
            <transmit-users>
                <channelmsg-tx-all>false</channelmsg-tx-all>
                <voice-tx-all>false</voice-tx-all>
                <videocapture-tx-all>false</videocapture-tx-all>
                <mediafile-tx-all>false</mediafile-tx-all>
                <desktopshare-tx-all>false</desktopshare-tx-all>
            </transmit-users>
            <files>
                <file name="TH06_05.おてんば恋娘 - (sweetmusic).mid">
                    <internalname>data_3.dat</internalname>
                    <filesize>69238</filesize>
                    <username>BaiRuoQiu</username>
                    <uploadtime>2023/06/26 01:38</uploadtime>
                </file>
                <file name="TH18_03.大吉キトゥン - (TouhouMIDICreator).mid">
                    <internalname>data_2.dat</internalname>
                    <filesize>40437</filesize>
                    <username>BaiRuoQiu</username>
                    <uploadtime>2023/06/26 01:37</uploadtime>
                </file>
            </files>
            <channelbans />
            <channel>
                
                <channel-id>4</channel-id>
                <name>***</name>
                <password />
                <topic>****************</topic>
                <diskquota>0</diskquota>
                <op-password />
                <max-users>30</max-users>
                <channel-type>23</channel-type>
                <userdata>0</userdata>
                <audio-codec>
                    <codec-type>3</codec-type>
                    <samplerate>48000</samplerate>
                    <channels>2</channels>
                    <application>2048</application>
                    <complexity>10</complexity>
                    <fec>true</fec>
                    <dtx>false</dtx>
                    <bitrate>32000</bitrate>
                    <vbr>true</vbr>
                    <vbr-constraint>false</vbr-constraint>
                    <framesize>1920</framesize>
                    <fpp>1</fpp>
                </audio-codec>
                <audio-config>
                    <enable-agc>false</enable-agc>
                    <gain-level>9600</gain-level>
                </audio-config>
                <transmit-users>
                    <channelmsg-tx-all>true</channelmsg-tx-all>
                    <voice-tx-all>true</voice-tx-all>
                    <videocapture-tx-all>true</videocapture-tx-all>
                    <mediafile-tx-all>true</mediafile-tx-all>
                    <desktopshare-tx-all>true</desktopshare-tx-all>
                </transmit-users>
                <files />
                <channelbans />
            </channel>
            <channel>
                
                <channel-id>3</channel-id>
                <name>***</name>
                <password />
                <topic>******************</topic>
                <diskquota>0</diskquota>
                <op-password />
                <max-users>30</max-users>
                <channel-type>1</channel-type>
                <userdata>0</userdata>
                <audio-codec>
                    <codec-type>3</codec-type>
                    <samplerate>24000</samplerate>
                    <channels>2</channels>
                    <application>2048</application>
                    <complexity>10</complexity>
                    <fec>true</fec>
                    <dtx>false</dtx>
                    <bitrate>64000</bitrate>
                    <vbr>true</vbr>
                    <vbr-constraint>false</vbr-constraint>
                    <framesize>960</framesize>
                    <fpp>1</fpp>
                </audio-codec>
                <audio-config>
                    <enable-agc>false</enable-agc>
                    <gain-level>9600</gain-level>
                </audio-config>
                <transmit-users>
                    <channelmsg-tx-all>true</channelmsg-tx-all>
                    <voice-tx-all>true</voice-tx-all>
                    <videocapture-tx-all>true</videocapture-tx-all>
                    <mediafile-tx-all>true</mediafile-tx-all>
                    <desktopshare-tx-all>true</desktopshare-tx-all>
                </transmit-users>
                <files />
                <channelbans />
            </channel>
            <channel>
                
                <channel-id>2</channel-id>
                <name>谛听殿</name>
                <password />
                <topic>*****************************</topic>
                <diskquota>0</diskquota>
                <op-password />
                <max-users>30</max-users>
                <channel-type>1</channel-type>
                <userdata>0</userdata>
                <audio-codec>
                    <codec-type>3</codec-type>
                    <samplerate>48000</samplerate>
                    <channels>2</channels>
                    <application>2049</application>
                    <complexity>10</complexity>
                    <fec>true</fec>
                    <dtx>false</dtx>
                    <bitrate>512000</bitrate>
                    <vbr>true</vbr>
                    <vbr-constraint>false</vbr-constraint>
                    <framesize>1920</framesize>
                    <fpp>1</fpp>
                </audio-codec>
                <audio-config>
                    <enable-agc>false</enable-agc>
                    <gain-level>9600</gain-level>
                </audio-config>
                <transmit-users>
                    <channelmsg-tx-all>true</channelmsg-tx-all>
                    <voice-tx-all>true</voice-tx-all>
                    <videocapture-tx-all>true</videocapture-tx-all>
                    <mediafile-tx-all>true</mediafile-tx-all>
                    <desktopshare-tx-all>true</desktopshare-tx-all>
                </transmit-users>
                <files />
                <channelbans />
            </channel>
        </channel>
    </permanent-channels>
</teamtalk>

### Steps to reproduce problem

mentioned above</div>

### PR DESCRIPTION
**Pull request by Nardol**
Fixes #1987

**Context**
The Android client could not connect to an IPv6-only TeamTalk server. On some Android devices/networks, name resolution via `getaddrinfo()` can also fail transiently (`EAI_AGAIN`), making connections unreliable even when IPv6 connectivity is available.

**What this changes**
- Fix UDP socket creation to match the resolved address family (AF_INET/AF_INET6) instead of always forcing IPv4.
- Make native resolution more robust on Android: retry on `EAI_AGAIN`, avoid problematic `getaddrinfo()` flags/constraints, and handle numeric IPv4/IPv6 literals without relying on the platform resolver.
- On Android, prefer `DnsResolver` (system ordering) and only fall back to UDP/53 DNS as a last resort (resolver timeouts/failures), with caching and logs limited to the fallback path.

**Compatibility / Risk**
- Keeps IPv4-only and dual-stack working.
- The UDP/53 fallback is intentionally last-resort (unencrypted) to avoid total failure when the system/NDK resolver is flaky.

**Testing**
- Verified on device: connects to IPv6-only server, dual-stack hostname (respects system preference), and IPv4-only server.

### CODE REVIEW

**Comment by Nardol** [comment]
Copilot Review suggestions applied, except hostname and port are two different fields and a TeamTalk server can be on a local network.

**Comment by bear101** [comment]
Is there a way to avoid changing files in TeamTalk DLL? It appears strange that it works on all other platform than Android.

Is it possible to make the DNS lookup in TeamTalkAndroid and always pass an IP-address (instead of a hostname) to TT_Connect()?

**Comment by Nardol** [comment]
I tried an Android-only approach (no changes in TeamTalk DLL / TeamTalkLib): resolve hostnames in `TeamTalkAndroid` (DnsResolver on API 29+, fallback to InetAddress) and always pass IP literals to `TT_Connect()`.
Result: even when we successfully resolve and pass an IPv6 literal, the connection still fails on Android.
Example logs:

```txt
DNS: Candidates for ipv6.hostname.tld -> [2001:xxxx:yyyy:zzzz::]
connect() to 2001:xxxx:yyyy:zzzz:: ... -> false
```

And even when entering the IPv6 literal directly:

```txt
connect(): host=2001:xxxx:yyyy:zzzz:: candidates=[2001:xxxx:yyyy:zzzz::]
connect() ... -> false
```

So this is not just a hostname/DNS issue. The Android native layer (JNI / underlying socket/connect path) appears to fail for IPv6, meaning an Android-only DNS workaround cannot fix #1987 on its own.

I pushed a branch called `android-ipv6-java-only` to test.

Proposed compromise:
We could keep the Android-side hostname resolution as a fallback to improve dual-stack hostname handling (and avoid DNS issues/timeouts), but it won’t fix IPv6-only/IPv6 literal connects.
The actual fix should be in the native layer so that `TT_Connect()` works with IPv6 literals on Android (proper IPv6 parsing + socket connect), ideally with additional Android-native logging (errno/family/address) to validate the fix.

File: Library/TeamTalkLib/myace/MyINet.cpp [hunk 1]
```diff
@@ -63,36 +71,115 @@ std::vector<ACE_INET_Addr> DetermineHostAddress(const ACE_TString& host, int por
     }
 
 #else
+    // Fast path for numeric literals (avoids platform resolver quirks).
+    // getaddrinfo() should handle numeric hosts, but on some Android devices
+    // it can still fail transiently (EAI_AGAIN) even for IPv6 literals.
+    const auto host_utf8_full = UnicodeToUtf8(host);
+    const char* host_utf8_cstr = host_utf8_full.c_str();
+    std::string host_utf8(host_utf8_cstr != nullptr ? host_utf8_cstr : "");
+    if (!host_utf8.empty() && host_utf8.front() == '[' && host_utf8.back() == ']')
```
Comment (bear101) [inline Library/TeamTalkLib/myace/MyINet.cpp]: Putting IPv6-address in brackets seems to be a Java-thing. The stripping should be done in Java, so `host` is just an IP-address. Should I look into fixing this or can you?

File: Library/TeamTalkLib/myace/MyINet.cpp [hunk 2]
```diff
@@ -112,13 +199,13 @@ std::vector<ACE_INET_Addr> DetermineHostAddress(const ACE_TString& host, int por
 #ifdef ACE_HAS_IPV6
         if (curr->ai_family == AF_INET6)
         {
-            addr.in6_.sin6_port = encode ? ACE_NTOHS(port) : port;
+            addr.in6_.sin6_port = encode ? ACE_HTONS(port) : port;
```
Comment (bear101) [inline Library/TeamTalkLib/myace/MyINet.cpp]: `encode` is always `true`, so it can be deleted.

File: Library/TeamTalkLib/myace/MyINet.cpp [hunk 3]
```diff
@@ -63,36 +71,115 @@ std::vector<ACE_INET_Addr> DetermineHostAddress(const ACE_TString& host, int por
...
+        if (ADDRINFOERROR == 0 || ADDRINFOERROR != EAI_AGAIN)
+            break;
+        ACE_OS::sleep(ACE_Time_Value(0, 200 * 1000)); // 200ms
+    }
 
     if (ADDRINFOERROR != 0)
     {
         errno = ADDRINFOERROR;
+#if defined(ANDROID)
+        __android_log_print(ANDROID_LOG_WARN, "bearware-native",
```
Comment (bear101) [inline Library/TeamTalkLib/myace/MyINet.cpp]: Use `MYTRACE` instead. It goes to Android log.

File: Library/TeamTalkLib/myace/MyINet.cpp [hunk 4]
```diff
@@ -63,36 +71,115 @@ std::vector<ACE_INET_Addr> DetermineHostAddress(const ACE_TString& host, int por
...
+    // UDP sockets so we want results for both transport types.
+    hints.ai_socktype = 0;
+    hints.ai_protocol = 0;
 
     addrinfo* res = nullptr;
 
-    const int ADDRINFOERROR = ACE_OS::getaddrinfo(UnicodeToUtf8(host).c_str(), nullptr, &hints, &res);
+    // Android's resolver may return EAI_AGAIN transiently even when DNS works
+    // (e.g. during network transitions). Retry a few times before giving up.
+    int ADDRINFOERROR = 0;
```
Comment (bear101) [inline Library/TeamTalkLib/myace/MyINet.cpp]: Uppercase is for constants. `ADDRINFOERROR` is not a constant.

File: Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java [hunk 5]
```diff
@@ -63,9 +68,27 @@
 import java.io.FileWriter;
 import java.io.IOException;
 import java.io.StringReader;
+import java.net.DatagramPacket;
```
Comment (bear101) [inline Client/TeamTalkAndroid/src/main/java/dk/bearware/backend/TeamTalkService.java]: Please move the DNS code to a separate class in `utils`. It is unrelated to TeamTalkService.

File: Library/TeamTalkLib/myace/MyINet.cpp [hunk 6]
```diff
@@ -51,23 +55,115 @@ std::vector<ACE_INET_Addr> DetermineHostAddress(const ACE_TString& host, uint16_
...
+    // Fast path for numeric literals (avoids platform resolver quirks).
+    // getaddrinfo() should handle numeric hosts, but on some Android devices
+    // it can still fail transiently (EAI_AGAIN) even for IPv6 literals.
+    const auto host_utf8_full = UnicodeToUtf8(host);
+    const char* host_utf8_cstr = host_utf8_full.c_str();
+    std::string host_utf8(host_utf8_cstr != nullptr ? host_utf8_cstr : "");
+
+    // IPv6 literals may include a zone index, e.g. "fe80::1%wlan0".
+    std::string v6addr = host_utf8;
+    std::string v6scope;
```
Comment (bear101) [inline Library/TeamTalkLib/myace/MyINet.cpp:71]: Why is it we need to set scope ID?

Comment (Nardol) [reply Library/TeamTalkLib/myace/MyINet.cpp:71]: Only when the literal includes a zone index (e.g. fe80::1%wlan0). That’s required for link‑local IPv6 to select the right interface; we don’t set a scope otherwise.

**Comment by bear101** [comment]
I'll resolve the conflicts with master but I plan to put `#ifdef ANDROID` around the new code in this merge-request. The new code complicates the code a lot and the problems with IPv6 are only related to Android.

Should there also be a check on Android platform level? In other words does newer Android devices also have this issue?

File: Library/TeamTalkLib/myace/MyINet.cpp [hunk 7]
```diff
@@ -37,26 +37,124 @@
...
+    auto percent = host_utf8.find('%');
```
Comment (bear101) [inline Library/TeamTalkLib/myace/MyINet.cpp:72]: `v6addr` and `v6scope` extraction could be simplified a lot by using a regular expression.

**Comment by Nardol** [comment]
> Should there also be a check on Android platform level? In other words does newer Android devices also have this issue?

Yes, I’m using a Pixel 8a running Android 16, and I’m experiencing this issue.

File: Library/TeamTalkLib/myace/MyINet.cpp (hunk 7 above)
Comment (Nardol) [reply Library/TeamTalkLib/myace/MyINet.cpp:72]: Regex would add complexity and has known perf/portability issues on Android/NDK; I’d prefer the current simple split.

**Comment by bear101** [comment]
@beqabeqa473 are you ok with the changes in this PR? In the TeamTalk DLL I've isolated the Android code, so none of the other platforms are affected.

**Comment by bear101** [comment]
@Nardol do you have an IP-address and port of a TeamTalk server that runs on IPv6 only?

**Comment by Nardol** [comment]
@bear101  I've just sent you the info privately.

**Comment by bear101** [comment]
Hm, on iOS it connects fine to the server you sent me on master branch. But if Android doesn't work without your changes then it's fine by me to merge it.

**Comment by bear101** [comment]
I'll fix the merge errors

**Comment by bear101** [comment]
Hm, I seem to remember testing this on your branch but when I test on master branch now I get this exception:
```
Process:dk.bearware.gui,PID:21183
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1450)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
	at java.net.InetAddress.getAllByName(InetAddress.java:787)
	at dk.bearware.utils.DnsUtils.resolveHostCandidatesForConnect(DnsUtils.java:189)
	at dk.bearware.backend.TeamTalkService.reconnect(TeamTalkService.java:638)
	at dk.bearware.gui.ServerListActivity.onServerClick(ServerListActivity.java:388)

```

**Comment by bear101** [comment]
@hwangsihu is it also crashing on your system? I wonder if it's some permissions that are messed up.

**Comment by hwangsihu** [comment]
Sorry, but how can I reproduce this? Just connect to a server that uses IPv6?

**Comment by bear101** [comment]
@Nardol hm, on Android 8.1 it crashes with the stack trace above.

When I try on Android 15 to connect to tt5eu.bearware.dk:10335 then it only tries IPv6 addresses as far I can see:
```
2026-01-11 10:02:12.849  9080-9080  bearware                dk.bearware.gui                      I  DNS fallback (udp53) for tt5eu.bearware.dk: dnsServers=[/10.0.2.3] privateDnsActive=false privateDnsServerName=null
2026-01-11 10:02:12.849  9080-9080  bearware                dk.bearware.gui                      I  DNS resolved (udp53) tt5eu.bearware.dk -> 2a01:4f8:c013:1167::1
2026-01-11 10:02:12.853  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:12.854  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:17.871  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:17.886  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:22.896  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:22.960  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:27.970  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:27.983  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:32.995  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:33.058  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:38.067  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:38.087  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:43.096  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:43.159  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:48.169  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:48.194  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:53.203  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:53.270  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:02:58.280  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:02:58.288  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:03:03.298  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:03:03.364  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
2026-01-11 10:03:08.374  9080-9080  bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 10:03:08.395  9080-9080  bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
```

**Comment by hwangsihu** [comment]
I can't connect to the server either.

By the way, didn't you recently change the library code regarding IPv6? Could it be conflicting with that?

**Comment by bear101** [comment]
> I can't connect to the server either.
> 
> By the way, didn't you recently change the library code regarding IPv6? Could it be conflicting with that?

Yes, you need to rebuild libTeamTalk5.so. But in the Android 8.1 call stack it doesn't event make it to `TeamTalk5.connect()`

**Comment by hwangsihu** [comment]
I tested it on Android 12, and I couldn't connect to the official servers, repeatedly receiving server connection failure messages. However, since I wasn't using the debug build, I couldn't check the logs.

**Comment by Nardol** [comment]
> @Nardol hm, on Android 8.1 it crashes with the stack trace above.
> 
> When I try on Android 15 to connect to tt5eu.bearware.dk:10335 then it only tries IPv6 addresses as far I can see:
> 
So two separate issues if I understand correctly?
For the second, is `tt5eu.bearware.dk:10335` IPv4-only? That's what it looks.
I might have forgoten this test case.

**Comment by bear101** [comment]
> > @Nardol hm, on Android 8.1 it crashes with the stack trace above.
> > When I try on Android 15 to connect to tt5eu.bearware.dk:10335 then it only tries IPv6 addresses as far I can see:
> 
> So two separate issues if I understand correctly? For the second, is `tt5eu.bearware.dk:10335` IPv4-only? That's what it looks. I might have forgoten this test case.

tt5eu.bearware.dk is both IPv4 and IPv6: 188.245.173.146 and 2a01:4f8:c013:1167::1

**Comment by Nardol** [comment]
> tt5eu.bearware.dk is both IPv4 and IPv6: 188.245.173.146 and 2a01:4f8:c013:1167::1

Yes, the hostname. But what about the server itself? Is it configured to listen on IPv4-only?

**Comment by bear101** [comment]
> > tt5eu.bearware.dk is both IPv4 and IPv6: 188.245.173.146 and 2a01:4f8:c013:1167::1
> 
> Yes, the hostname. But what about the server itself? Is it configured to listen on IPv4-only?

It binds to both:
```
        <bind-ip>188.245.173.146</bind-ip>
        <bind-ip>2a01:4f8:c013:1167::1</bind-ip>
```

**Comment by Nardol** [comment]
@bear101 I pushed a branch which does two things:

1. Moves `InetAddress.getAllByName()` to a background executor to avoid `NetworkOnMainThreadException` on API 27.
2. If `DnsResolver` returns only one family (e.g. IPv6), it fills the missing family using UDP fallback and merges the list, so IPv4 is actually tried.

I also added a temporary log of `connectHosts` to verify what’s being attempted.

Branch: `fix/android-dns-fallback` (commit 3c5c9193c).

Before I open a PR, could you test and tell me if it fixes both issues?

**Comment by bear101** [comment]
With this change I can connect to tt5eu.bearware.dk with API 27.

But then I tried API 35 and it cannot connect to tt5eu.bearware.dk

```
2026-01-11 21:08:39.308 11141-11141 bearware                dk.bearware.gui                      I  DNS fallback (udp53) for tt5eu.bearware.dk: dnsServers=[/10.0.2.3] privateDnsActive=false privateDnsServerName=null
2026-01-11 21:08:39.308 11141-11141 bearware                dk.bearware.gui                      I  DNS resolved (udp53) tt5eu.bearware.dk -> 2a01:4f8:c013:1167::1
2026-01-11 21:08:39.309 11141-11141 bearware                dk.bearware.gui                      I  DNS candidates for tt5eu.bearware.dk: [2a01:4f8:c013:1167::1, 188.245.173.146]
2026-01-11 21:08:39.311 11141-11141 bearware                dk.bearware.gui                      I  connect() to 2a01:4f8:c013:1167::1:10335 udp 10335 enc=false -> true
2026-01-11 21:08:39.312 11141-11141 bearware                dk.bearware.gui                      I  Failed to connect tt5eu.bearware.dk:10335
```

**Comment by Nardol** [comment]
I updated the same branch with a fix for API 35.
Issue: connect() returns true for IPv6 (attempt started), then fails later; our loop stops, so IPv4 is never tried.
Fix: on onConnectFailed() we now try the next DNS candidate before giving up.
New commit: 389cd3cb7 on branch fix/android-dns-fallback.
Could you retest API 35 with this?

Not sure this is the cleanest approach, but it should verify the suspected failure path.

**Comment by bear101** [comment]
@Nardol I've reverted the commit in #3097. Can you create a new pull request from fix/android-dns-fallback where the "revert" is reverted? Then that pull request can be used for future discussions
