### PR TITLE
fix(Server): Prevent accidental operator inheritance on channel ID reuse

### LINKED ISSUE #2201: Security vulnerability: user can become a channel operator by accident
### Description

This problem occurs because the information about channel operators is stored in the form where only the channel ID is recorded.
So if the administrator deletes some channel and creates a new one with the same ID, all users who had some extra rights to the old channel immediately get the same rights in the new one.

Not checked yet, but I think that with other extra rights and per user settings this situation will be the same.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [X] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

I suggest that when some channel is being deleted while server is running and when server starts / stops and checks the configuration all records that belong to channels that don't exist anymore should be also deleted from the configuration.

### Actual behavior

When you delete a channel and create a new one and it gets the same ID as the old one, users who were old channel operators become the new channel operators too.

### Steps to reproduce problem

1. Create a permanent channel on your server;
2. Set some user as the channel operator;
3. Open Teamtalk config xml file and write down an ID of the newly created channel;
4. Delete the channel;
5. Create a new permanent channel;
6. Notice that its ID is the same as the deleted one;
7. Ask the user who was the previous channel operator to re-login;
8. Find that now he/she is a new channel operator too.

### PR DESCRIPTION
**Pull request by BlindMaster24**
Resolves #2201 by implementing a mechanism to purge stale channel operator rights upon channel deletion.
A new public method, ServerXML::CleanupChannelOperators(int channelId), is introduced to iterate through users and remove operator privileges for a specific channel ID. The ServerGuard::OnChannelRemoved method has been updated to call this new function.

### CODE REVIEW

File: Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp [hunk 1]
```diff
@@ -1493,6 +1493,67 @@ namespace teamtalk{
...
+        // Get the root <users> element
+        TiXmlElement* usersElement = GetUsersElement();
+        if (!usersElement)
+        {
+            // No users element, so nothing to do
+            return false;
+        }
+
+        // Iterate through each <user> element
+        TiXmlElement* userElement = usersElement->FirstChildElement("user");
```
Comment (bear101) [inline Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp]: Use `GetNextUser` to iterate through the user accounts instead. This will remove a lot of code.

Comment (bear101) [reply Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp]: Then look for channel-ID in `UserAccount::auto_op_channels`

**Review by bear101 — CHANGES_REQUESTED** [review]

**Comment by amirmahdifard** [comment]
@bear101 But I think your suggestion was better, to store channel path instead of channel id.

**Comment by BlindMaster24** [comment]
@amirmahdifard After some analysis, I realized that storing the path is reliable, but it's not necessary in our case. Either way, we'd have to remove the channel operator rights from users every time, so yeah.

**Comment by BlindMaster24** [comment]
@bear101 Thx. How'd I not notice that before, lol. But thx again for the tip.

**Comment by BlindMaster24** [comment]
@amirmahdifard And if you're wondering why, here's the short version.
If someone manually changes a channel's path in the XML by moving it, the entire logic becomes useless. For this to work properly with paths instead of IDs, the whole XML would need to be converted to a single standard. This adds extra lines of code, plus I'd have to do what I'm doing now and even more.
Specifically, on top of deleting, it seems I'd also have to check where a given channel is and search for it wherever it might be. An ID isn't susceptible to these problems.
@bear101 what do you think, am I correct or am I exaggerating?

**Comment by BlindMaster24** [comment]
@bear101 Done!

File: Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp [hunk 2]
```diff
@@ -1493,6 +1493,44 @@ namespace teamtalk{
...
+        {
+            usernamesToRemove.push_back(UnicodeToUtf8(currentUser.username).c_str());
+            currentUser.auto_op_channels.erase(deletedChannelID);
+            usersToModify.push_back(currentUser);
+            overallModified = true;
+        }
+        currentUser = UserAccount();
+    }
+
+    if (overallModified)
```
Comment (bear101) [inline Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp]: You don't need the `overallModified` variable. Just check `usersToModify.size()`.

File: Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp [hunk 3]
```diff
@@ -1493,6 +1493,44 @@ namespace teamtalk{
...
+    {
+        for (const auto& username : usernamesToRemove)
```
Comment (bear101) [inline Library/TeamTalkLib/bin/ttsrv/ServerXML.cpp]: You don't need `usernamesToRemove` vector. Just use run the loop below like this:
```
        for (const auto& userAcc : usersToModify)
        {
            RemoveUser(UnicodeToUtf8(userAcc.username).c_str()););
            AddNewUser(userAcc);
        }
```

**Review by bear101 — CHANGES_REQUESTED** [review]

**Comment by BlindMaster24** [comment]
@bear101
After review, I am keeping the two-loop approach.
Mixing mutation operations (remove/add) within a single pass is prone to side effects and makes the logic less predictable. The current design isolates the mutation logic, making it more robust and resilient to future changes. The single-loop alternative is brittle by comparison.
My priority here is long-term stability. However, I want to ensure I'm not missing your perspective. Could you elaborate on the benefits of the single-loop approach?

**Comment by BlindMaster24** [comment]
@bear101
To add some context for my persistence on this point:
My goal isn't just to close an issue, but to ensure the solution we merge is as robust and maintainable as possible. I'm focused on this detail because I believe preventing even small amounts of technical debt is critical for the long-term health of the codebase.

**Comment by BlindMaster24** [comment]
@bear101
Here is a concrete failure scenario for the single-loop design:
Scenario: A future requirement is added to rename user accounts on channel deletion (e.g., add a _legacy suffix).
The single-loop logic fails as follows:
1. 
usersToModify holds the UserAccount with the new name (user_legacy).
2. 
RemoveUser("user_legacy") is called. It fails, as the XML still contains "user".
3. 
AddNewUser() is called, creating a duplicate account.
Outcome: Data corruption. The original user is never removed.
The two-loop implementation prevents this by design. It decouples the list of original usernames for removal from the modified user objects for addition. Therefore, the two-loop design is the only correct implementation to prevent this class of bugs.

**Comment by beqabeqa473** [comment]
what is real purpose of renaming a user on channel deletion? Please provide real usecase, which an be applicable.

**Comment by jeremyp3** [comment]
@BlindMaster24 as we've already told you dozens of times, stop spamming! you can edit your last comment if you have something to add rather than making 3 in less than 10 minutes. it's pointless. your PR won't be merged any faster.

**Comment by BlindMaster24** [comment]
@beqabeqa473 The scenario is a hypothetical to demonstrate the design flaw. The focus is on structural robustness, not the example's specifics.

**Comment by BlindMaster24** [comment]
@jeremyp3 Dude, get context before you post.

**Comment by BlindMaster24** [comment]
@jeremyp3 Nothing's ready to merge yet. But point taken.

**Comment by BlindMaster24** [comment]
@bear101
Finalizing this with the two-loop implementation.
The single-loop design has a clear data-integrity flaw. As the author, I can't submit code I know is unsafe.
I'm curious about the trade-off. What was the intended technical benefit of the single-loop approach?

**Comment by Nardol** [comment]
@BlindMaster24 You perfectly could have merged all your comment in one, which is a point @jeremyp3 talked about. And editing a comment could avoid receiving a lot of mails as it just appened.
Imagine if everybody would proceed as you do, following a repository would be a nightmar. So please, take this suggestion in account, which would result in a better experience for everybody and won't make your work less considered :blush:

**Comment by BlindMaster24** [comment]
@Nardol k

**Comment by bear101** [comment]
Please change it to the single loop (where username is from the stored UserAccount). You should always use a minimum number of variables. The more variables the more states. More states means more possible errors.

**Comment by BlindMaster24** [comment]
> Please change it to the single loop (where username is from the stored UserAccount). You should always use a minimum number of variables. The more variables the more states. More states means more possible errors.

@bear101 The principle of minimizing state is textbook correct. However, its application here is inverted.
The single-loop trades explicit, managed state (the variables) for an implicit, unmanaged state dependency on the lookup key. The latter is the more significant source of errors.

**Comment by bear101** [comment]
Why do you see using `usersToModify` as becoming an unmanaged state?

Having two vectors use more memory and contains duplicate information.

**Comment by BlindMaster24** [comment]
> Why do you see using `usersToModify` as becoming an unmanaged state?
> 
> Having two vectors use more memory and contains duplicate information.

@bear101
The duplication is the point. It decouples lookup from modification.
The single loop merges them, creating an unsafe dependency on the username. That's the unmanaged state.
The memory cost is trivial for the safety it provides.

**Comment by beqabeqa473** [comment]
Just do what was asked. Your hypotetical examples are not real world examples. If for some reason, this will be needed in the future, i am sure corresponding refactor will be made. So, if you want your pr to be merged, don't delay it yourself.

**Comment by BlindMaster24** [comment]
> Just do what was asked. Your hypotetical examples are not real world examples. If for some reason, this will be needed in the future, i am sure corresponding refactor will be made. So, if you want your pr to be merged, don't delay it yourself.

@beqabeqa473 My job is to ship a correct fix, not a fast one.
"Refactor later" is how you create technical debt. This codebase has enough.
The simple way is unsafe.

**Comment by BlindMaster24** [comment]
@bear101 Merged. The test passes.

**Comment by BlindMaster24** [comment]
@bear101 The tests pass, I explained with arguments why my changes aren't just random, what else is needed?

**Comment by bear101** [comment]
Remove `usernamesToRemove` and the pull request will be merge. Your reasons to keep it are not sound.

> @bear101 The tests pass, I explained with arguments why my changes aren't just random, what else is needed?

**Comment by BlindMaster24** [comment]
@bear101
Fine. I will remove the safety mechanism as requested.
Let the record show that I, as the author, consider this change unsafe and a violation of standard data integrity practices. I am implementing it against my professional judgment, under your direction as maintainer.
When this implementation inevitably fails and causes data corruption, I will refer all future issue reports back to this conversation, and to your decision to override a safe design.

**Comment by amirmahdifard** [comment]
@BlindMaster24 Just do what @bear101 asks. he is the owner of the project. I also agree with @bear101 because that has less code and less loops.

**Comment by BlindMaster24** [comment]
> @BlindMaster24 Just do what @bear101 asks. he is the owner of the project. I also agree with @bear101 because that has less code and less loops.

@amirmahdifard Before agreeing, try writing a few projects on your own, and you'll see that less code isn't always better.
If you haven't learned to read, I agree to do what @bear101 suggested, but under his responsibility.

**Comment by amirmahdifard** [comment]
@BlindMaster24 but in this case, what @bear101 is asking is meaningful and correct, because it's directly assighned to the useraccount and doesn't check more things. And if he asks you to do it, just do it so he will merge it. What are you waiting for now?

**Comment by amirmahdifard** [comment]
@BlindMaster24 can you please do what he asked you so we can have this fix in server 5.19 server? he has convurted your pull request to draffed and that means he is waiting for you to do this. Thanks

**Comment by BlindMaster24** [comment]
> @BlindMaster24 can you please do what he asked you so we can have this fix in server 5.19 server? he has convurted your pull request to draffed and that means he is waiting for you to do this. Thanks

@amirmahdifard Busy now. Will get to it when I have time. Not stupid, lol. Understand how this works on GitHub.
