### PR TITLE
Fix default status message value

### LINKED ISSUE #2804: Default Status?
### Description

Hi,
I am not sure if this is a bug, but on new installs of TeamTalk, or after updating to 5.19, the default status message is already set in prefrences.
general_/statusmsg
this happens after updating to 5.19.0 latest version. It also seams to affect new profiles.
Thanks for reading!

### Application

- [x] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [x] Windows
- [x] macOS
- [ ] Android
- [ ] iOS
- [x] Linux

### Expected behavior

There should be no default status message before one is set.

### Actual behavior

general_/statusmsg

### Steps to reproduce problem

Create a new profile, or reinstall TT with default settings.
Going to the main Prefrences settings you will see a default status message already set called general_/statusmsg

### PR DESCRIPTION
**Pull request by CoBC**
Fixed #2804

### CODE REVIEW

File: Client/qtTeamTalk/utilui.cpp [hunk 1]
```diff
@@ -181,6 +181,12 @@ void migrateSettings()
         // msgtimestamp removed in 5.5 format
         ttSettings->remove("display/msgtimestamp");
     }
+    if (!versionSameOrLater(iniversion, "5.6"))
```
Comment (bear101) [inline Client/qtTeamTalk/utilui.cpp:184]: Don't you need to bump SETTINGS_VERSION to 5.6?

**Comment by bear101** [comment]
Here's my idea:
```
if (ttSettings->value(SETTINGS_STATUSBAR_ACTIVEEVENTS, SETTINGS_STATUSBAR_ACTIVEEVENTS_DEFAULT) == SETTINGS_STATUSBAR_ACTIVEEVENTS_DEFAULT)
{
    ttSettings->remove(SETTINGS_STATUSBAR_ACTIVEEVENTS);
}
else
{
   ttSettings->setValue(SETTINGS_STATUSBAR_ACTIVEEVENTS, newvalue);
}
```

**Comment by bear101** [comment]
You can see my idea in #2830
